name: Node.js CI/CD Pipeline

# This will trigger the workflow on push events to the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # This job installs dependencies, runs tests, and deploys (if needed)
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Use the Node.js version that matches your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests (if you have tests in your Node.js project)
      - name: Run tests
        run: npm test

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          ssh-keyscan -H 159.223.49.147 >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean Droplet
        run: |
          ssh root@159.223.49.147 << 'EOF'
            cd Flymya/nodejs-edp
            git pull origin main
            npm install --production
            npm run build
            pm2 restart app # Modify based on your setup
          EOF
